export type Database = {
  public: {
    Tables: {
      customers: {
        Row: {
          id: string;
          namn: string;
          telefon: string;
          mejl: string;
          user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          namn: string;
          telefon: string;
          mejl: string;
          user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          namn?: string;
          telefon?: string;
          mejl?: string;
          user_id?: string | null;
          created_at?: string;
        };
      };
      cars: {
        Row: {
          id: string;
          regnummer: string;
          marke: string;
          modell: string;
          ar: number;
          miltal: number;
          skick: string;
          skick_kommentar: string;
          utrustning: string[];
          status: string;
          notes: string;
          auktion_slut: string | null;
          vinnande_bud_id: string | null;
          customer_id: string;
          access_token: string;
          kund_beslut: string;
          kund_beslut_at: string | null;
          sales_type: string;
          direct_bid_estimate: number | null;
          brokerage_estimate_low: number | null;
          brokerage_estimate_high: number | null;
          crm_status: string | null;
          crm_status_updated_at: string | null;
          crm_lost_reason: string | null;
          condition_report: Record<string, unknown>;
          momsbil: boolean;
          reservationspris: number | null;
          startbud: number | null;
          trade_in_interest: boolean;
          trade_in_wants: string;
          pickup_status: string;
          pickup_at: string | null;
          payment_received_at: string | null;
          hidden_from_dealers: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          regnummer: string;
          marke: string;
          modell: string;
          ar: number;
          miltal: number;
          skick: string;
          skick_kommentar?: string;
          utrustning?: string[];
          status?: string;
          notes?: string;
          auktion_slut?: string | null;
          vinnande_bud_id?: string | null;
          customer_id: string;
          access_token?: string;
          kund_beslut?: string;
          kund_beslut_at?: string | null;
          sales_type?: string;
          direct_bid_estimate?: number | null;
          brokerage_estimate_low?: number | null;
          brokerage_estimate_high?: number | null;
          crm_status?: string | null;
          crm_status_updated_at?: string | null;
          crm_lost_reason?: string | null;
          condition_report?: Record<string, unknown>;
          momsbil?: boolean;
          reservationspris?: number | null;
          startbud?: number | null;
          trade_in_interest?: boolean;
          trade_in_wants?: string;
          pickup_status?: string;
          pickup_at?: string | null;
          payment_received_at?: string | null;
          hidden_from_dealers?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          regnummer?: string;
          marke?: string;
          modell?: string;
          ar?: number;
          miltal?: number;
          skick?: string;
          skick_kommentar?: string;
          utrustning?: string[];
          status?: string;
          notes?: string;
          auktion_slut?: string | null;
          vinnande_bud_id?: string | null;
          customer_id?: string;
          access_token?: string;
          kund_beslut?: string;
          kund_beslut_at?: string | null;
          sales_type?: string;
          direct_bid_estimate?: number | null;
          brokerage_estimate_low?: number | null;
          brokerage_estimate_high?: number | null;
          crm_status?: string | null;
          crm_status_updated_at?: string | null;
          crm_lost_reason?: string | null;
          condition_report?: Record<string, unknown>;
          momsbil?: boolean;
          reservationspris?: number | null;
          startbud?: number | null;
          trade_in_interest?: boolean;
          trade_in_wants?: string;
          pickup_status?: string;
          pickup_at?: string | null;
          payment_received_at?: string | null;
          hidden_from_dealers?: boolean;
          created_at?: string;
        };
      };
      brokerage_offers: {
        Row: {
          id: string;
          car_id: string;
          dealer_id: string;
          expected_sale_price: number;
          commission_kr: number;
          estimated_days: number;
          kommentar: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          dealer_id: string;
          expected_sale_price: number;
          commission_kr: number;
          estimated_days: number;
          kommentar?: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          dealer_id?: string;
          expected_sale_price?: number;
          commission_kr?: number;
          estimated_days?: number;
          kommentar?: string;
          status?: string;
          created_at?: string;
        };
      };
      car_images: {
        Row: {
          id: string;
          car_id: string;
          storage_url: string;
          ordning: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          storage_url: string;
          ordning: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          storage_url?: string;
          ordning?: number;
          created_at?: string;
        };
      };
      dealers: {
        Row: {
          id: string;
          foretagsnamn: string;
          orgnr: string;
          kontaktperson: string;
          telefon: string;
          mejl: string;
          godkand: boolean;
          user_id: string | null;
          created_at: string;
          fornamn: string;
          efternamn: string;
          faktura_epost: string;
          moderbolag: string;
          adresser: string[];
          organisationsnummer: string[];
          f_skatt_ok: boolean;
          moms_registrerad: boolean;
          verifierad_at: string | null;
          bankid_verifierad_at: string | null;
        };
        Insert: {
          id?: string;
          foretagsnamn?: string;
          orgnr?: string;
          kontaktperson?: string;
          telefon?: string;
          mejl?: string;
          godkand?: boolean;
          user_id?: string | null;
          created_at?: string;
          fornamn?: string;
          efternamn?: string;
          faktura_epost?: string;
          moderbolag?: string;
          adresser?: string[];
          organisationsnummer?: string[];
          f_skatt_ok?: boolean;
          moms_registrerad?: boolean;
          verifierad_at?: string | null;
          bankid_verifierad_at?: string | null;
        };
        Update: {
          id?: string;
          foretagsnamn?: string;
          orgnr?: string;
          kontaktperson?: string;
          telefon?: string;
          mejl?: string;
          godkand?: boolean;
          user_id?: string | null;
          created_at?: string;
          fornamn?: string;
          efternamn?: string;
          faktura_epost?: string;
          moderbolag?: string;
          adresser?: string[];
          organisationsnummer?: string[];
          f_skatt_ok?: boolean;
          moms_registrerad?: boolean;
          verifierad_at?: string | null;
          bankid_verifierad_at?: string | null;
        };
      };
      bids: {
        Row: {
          id: string;
          car_id: string;
          dealer_id: string;
          belopp: number;
          kommentar: string;
          status: string;
          max_bid: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          dealer_id: string;
          belopp: number;
          kommentar?: string;
          status?: string;
          max_bid?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          dealer_id?: string;
          belopp?: number;
          kommentar?: string;
          status?: string;
          max_bid?: number | null;
          created_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          regnummer: string;
          telefon: string;
          car_id: string | null;
          kontaktad: boolean;
          lan: string;
          postnummer: string;
          miltal: number | null;
          guidance_requested: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          regnummer?: string;
          telefon?: string;
          car_id?: string | null;
          kontaktad?: boolean;
          lan?: string;
          postnummer?: string;
          miltal?: number | null;
          guidance_requested?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          regnummer?: string;
          telefon?: string;
          car_id?: string | null;
          kontaktad?: boolean;
          lan?: string;
          postnummer?: string;
          miltal?: number | null;
          guidance_requested?: boolean;
          created_at?: string;
        };
      };
      car_activities: {
        Row: {
          id: string;
          car_id: string;
          type: string;
          title: string;
          body: string;
          data: Record<string, unknown>;
          created_by: string | null;
          created_by_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          type?: string;
          title?: string;
          body?: string;
          data?: Record<string, unknown>;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          type?: string;
          title?: string;
          body?: string;
          data?: Record<string, unknown>;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
        };
      };
      car_reminders: {
        Row: {
          id: string;
          car_id: string;
          remind_at: string;
          title: string;
          done: boolean;
          done_at: string | null;
          created_by: string | null;
          created_by_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          remind_at: string;
          title?: string;
          done?: boolean;
          done_at?: string | null;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          remind_at?: string;
          title?: string;
          done?: boolean;
          done_at?: string | null;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
        };
      };
      valuation_requests: {
        Row: {
          id: string;
          car_id: string;
          from_user_id: string | null;
          from_user_name: string;
          to_user_id: string | null;
          to_user_name: string;
          message: string;
          status: string;
          response_value: number | null;
          response_expected_sale: number | null;
          response_comment: string;
          responded_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          from_user_id?: string | null;
          from_user_name?: string;
          to_user_id?: string | null;
          to_user_name?: string;
          message?: string;
          status?: string;
          response_value?: number | null;
          response_expected_sale?: number | null;
          response_comment?: string;
          responded_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          from_user_id?: string | null;
          from_user_name?: string;
          to_user_id?: string | null;
          to_user_name?: string;
          message?: string;
          status?: string;
          response_value?: number | null;
          response_expected_sale?: number | null;
          response_comment?: string;
          responded_at?: string | null;
          created_at?: string;
        };
      };
      admin_users: {
        Row: {
          id: string;
          name: string;
          email: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id: string;
          name?: string;
          email: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          role?: string;
          created_at?: string;
        };
      };
      notifications_log: {
        Row: {
          id: string;
          typ: string;
          mottagare_mejl: string;
          skickat_at: string;
          status: string;
          referens_id: string | null;
          detaljer: string;
        };
        Insert: {
          id?: string;
          typ?: string;
          mottagare_mejl?: string;
          skickat_at?: string;
          status?: string;
          referens_id?: string | null;
          detaljer?: string;
        };
        Update: {
          id?: string;
          typ?: string;
          mottagare_mejl?: string;
          skickat_at?: string;
          status?: string;
          referens_id?: string | null;
          detaljer?: string;
        };
      };
      quote_requests: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          search_option: string;
          regnummer: string;
          miltal: number;
          buying_stage: string;
          budget: string;
          payment_type: string;
          monthly_payment: string;
          car_model: string;
          fuel_type: string;
          link_or_seller: string;
          target_car: string;
          additional_requests: string;
          firstname: string;
          lastname: string;
          email: string;
          phone: string;
          preferred_time: string;
          status: string;
          handled_by: string | null;
          notes: string;
          quiz_answers: Record<string, unknown> | null;
          has_trade_in: boolean;
          trade_in_reg: string;
          current_loan: string;
          current_interest_rate: string;
          desired_monthly_cost: string;
          access_token: string | null;
          access_token_created_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          search_option?: string;
          regnummer?: string;
          miltal?: number;
          buying_stage?: string;
          budget?: string;
          payment_type?: string;
          monthly_payment?: string;
          car_model?: string;
          fuel_type?: string;
          link_or_seller?: string;
          target_car?: string;
          additional_requests?: string;
          firstname?: string;
          lastname?: string;
          email?: string;
          phone?: string;
          preferred_time?: string;
          status?: string;
          handled_by?: string | null;
          notes?: string;
          quiz_answers?: Record<string, unknown> | null;
          has_trade_in?: boolean;
          trade_in_reg?: string;
          current_loan?: string;
          current_interest_rate?: string;
          desired_monthly_cost?: string;
          access_token?: string | null;
          access_token_created_at?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          search_option?: string;
          regnummer?: string;
          miltal?: number;
          buying_stage?: string;
          budget?: string;
          payment_type?: string;
          monthly_payment?: string;
          car_model?: string;
          fuel_type?: string;
          link_or_seller?: string;
          target_car?: string;
          additional_requests?: string;
          firstname?: string;
          lastname?: string;
          email?: string;
          phone?: string;
          preferred_time?: string;
          status?: string;
          handled_by?: string | null;
          notes?: string;
          quiz_answers?: Record<string, unknown> | null;
          has_trade_in?: boolean;
          trade_in_reg?: string;
          current_loan?: string;
          current_interest_rate?: string;
          desired_monthly_cost?: string;
          access_token?: string | null;
          access_token_created_at?: string | null;
        };
      };
      quote_suggestions: {
        Row: {
          id: string;
          quote_request_id: string;
          car_description: string;
          car_image_url: string;
          price: number;
          monthly_cost: number | null;
          link: string;
          admin_comment: string;
          status: string;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          quote_request_id: string;
          car_description?: string;
          car_image_url?: string;
          price?: number;
          monthly_cost?: number | null;
          link?: string;
          admin_comment?: string;
          status?: string;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          quote_request_id?: string;
          car_description?: string;
          car_image_url?: string;
          price?: number;
          monthly_cost?: number | null;
          link?: string;
          admin_comment?: string;
          status?: string;
          sent_at?: string | null;
          created_at?: string;
        };
      };
      dealer_proposals: {
        Row: {
          id: string;
          car_id: string;
          dealer_id: string | null;
          dealer_name: string;
          inbytespris: number;
          kund_nuvarande_manad: number;
          kund_nuvarande_ranta: number;
          kund_lanerest: number;
          dealtyp: string;
          offered_car_id: string | null;
          erbjuden_marke: string;
          erbjuden_modell: string;
          erbjuden_ar: number | null;
          erbjuden_miltal: number | null;
          erbjuden_skick: string;
          erbjuden_dack: string;
          erbjuden_bild_urls: string[];
          manadskostnad: number;
          loptid_manader: number;
          ranta: number;
          garanti_ar: number;
          vinterdack_inkl: boolean;
          personligt_meddelande: string;
          status: string;
          sent_at: string | null;
          viewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          car_id: string;
          dealer_id?: string | null;
          dealer_name?: string;
          inbytespris?: number;
          kund_nuvarande_manad?: number;
          kund_nuvarande_ranta?: number;
          kund_lanerest?: number;
          dealtyp?: string;
          offered_car_id?: string | null;
          erbjuden_marke?: string;
          erbjuden_modell?: string;
          erbjuden_ar?: number | null;
          erbjuden_miltal?: number | null;
          erbjuden_skick?: string;
          erbjuden_dack?: string;
          erbjuden_bild_urls?: string[];
          manadskostnad?: number;
          loptid_manader?: number;
          ranta?: number;
          garanti_ar?: number;
          vinterdack_inkl?: boolean;
          personligt_meddelande?: string;
          status?: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          car_id?: string;
          dealer_id?: string | null;
          dealer_name?: string;
          inbytespris?: number;
          kund_nuvarande_manad?: number;
          kund_nuvarande_ranta?: number;
          kund_lanerest?: number;
          dealtyp?: string;
          offered_car_id?: string | null;
          erbjuden_marke?: string;
          erbjuden_modell?: string;
          erbjuden_ar?: number | null;
          erbjuden_miltal?: number | null;
          erbjuden_skick?: string;
          erbjuden_dack?: string;
          erbjuden_bild_urls?: string[];
          manadskostnad?: number;
          loptid_manader?: number;
          ranta?: number;
          garanti_ar?: number;
          vinterdack_inkl?: boolean;
          personligt_meddelande?: string;
          status?: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
