import type { Forhandlare } from './forhandlare.types';

export const FALLBACK_FORHANDLARE: Forhandlare[] = [
  {
    id: 'f1',
    slug: 'alexander-berg',
    name: 'Alexander Berg',
    certifiering: 'Master',
    bio: 'Bilbranschens veteran med över 15 års erfarenhet. Specialiserad på premium- och lyxbilar. Alexander har hjälpt över 400 kunder till en bättre affär.',
    specialties: ['Lyxbilar', 'Premium', 'Inbyte', 'Finansiering'],
    languages: ['Svenska', 'Engelska'],
    city: 'Stockholm',
    avatar_url: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 4995,
    rating: 4.9,
    review_count: 47,
    deal_count: 412,
    avg_saving_kr: 22000,
    response_time_hours: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'f2',
    slug: 'maria-lindqvist',
    name: 'Maria Lindqvist',
    certifiering: 'Elite',
    bio: 'Certifierad förhandlare med fokus på el- och hybridbilar. Maria håller koll på marknadens snabbaste segment och vet exakt var marginalerna finns.',
    specialties: ['Elbilar', 'Hybrid', 'Laddhybrid', 'TCO'],
    languages: ['Svenska', 'Engelska', 'Tyska'],
    city: 'Göteborg',
    avatar_url: 'https://images.pexels.com/photos/3760263/pexels-photo-3760263.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 4995,
    rating: 4.8,
    review_count: 31,
    deal_count: 203,
    avg_saving_kr: 18000,
    response_time_hours: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'f3',
    slug: 'daniel-eriksson',
    name: 'Daniel Eriksson',
    certifiering: 'Elite',
    bio: 'Prisförhandlare med bakgrund som bilhandlare. Daniel vet vad handlaren betalat och var marginalen finns – och utnyttjar det för din räkning.',
    specialties: ['Prisförhandling', 'Finansiering', 'Inbyte'],
    languages: ['Svenska', 'Engelska'],
    city: 'Malmö',
    avatar_url: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 4995,
    rating: 4.8,
    review_count: 28,
    deal_count: 178,
    avg_saving_kr: 19000,
    response_time_hours: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'f4',
    slug: 'sofia-nilsson',
    name: 'Sofia Nilsson',
    certifiering: 'Senior',
    bio: 'Specialist på familjebilar och säkerhet. Sofia hjälper dig hitta rätt bil för hela familjen – med fokus på säkerhet, utrymme och driftskostnad.',
    specialties: ['Familjebilar', 'SUV', 'Säkerhet', 'Driftskostnad'],
    languages: ['Svenska', 'Norska'],
    city: 'Uppsala',
    avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 4995,
    rating: 4.7,
    review_count: 19,
    deal_count: 94,
    avg_saving_kr: 15000,
    response_time_hours: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'f5',
    slug: 'johan-karlsson',
    name: 'Johan Karlsson',
    certifiering: 'Senior',
    bio: 'Allround-förhandlare med bred marknadskännedom. Johan hanterar allt från småbilar till transportbilar och vet värdet av varje modell.',
    specialties: ['Transportbilar', 'Småbilar', 'Inbyte'],
    languages: ['Svenska', 'Engelska'],
    city: 'Stockholm',
    avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 4995,
    rating: 4.7,
    review_count: 22,
    deal_count: 112,
    avg_saving_kr: 16000,
    response_time_hours: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'f6',
    slug: 'emma-johansson',
    name: 'Emma Johansson',
    certifiering: 'Certifierad',
    bio: 'Ny certifierad förhandlare med starkt fokus på kundservice. Emma är särskilt skicklig på att hitta rätt bil för första köparen.',
    specialties: ['Första bilen', 'Budget', 'Bilkörkort'],
    languages: ['Svenska', 'Engelska'],
    city: 'Göteborg',
    avatar_url: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=400',
    fee_kr: 3995,
    rating: 4.6,
    review_count: 12,
    deal_count: 41,
    avg_saving_kr: 12000,
    response_time_hours: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export function getFallbackForhandlareBySlug(slug: string): Forhandlare | null {
  return FALLBACK_FORHANDLARE.find(f => f.slug === slug) ?? null;
}
