import { ArrowRight, Check, Handshake, ShieldCheck, Sparkles, TrendingUp, Wallet } from 'lucide-react';

export default function FormedlingPartnerPage() {
  return <div className="min-h-screen bg-[#0a0f1a] text-white">
    <header className="h-16 border-b border-white/8 flex items-center justify-between px-5 lg:px-10"><a href="/formedling" className="text-[21px] font-black">Bilto<span className="text-bilto-400">.</span></a><a href="/formedling/forhandlare" className="text-[14px] text-white/65 hover:text-white">Logga in</a></header>
    <main>
      <section className="px-5 py-24 lg:py-32"><div className="max-w-5xl mx-auto grid lg:grid-cols-2 gap-14 items-center"><div><p className="text-[12px] font-bold text-bilto-400 uppercase tracking-[0.2em] mb-5">För förmedlare</p><h1 className="text-[42px] sm:text-[64px] font-black leading-[.98] tracking-[-.04em]">Få fler bilar att sälja.</h1><p className="text-[17px] text-white/55 leading-relaxed mt-7 max-w-md">Få tillgång till bilägare som aktivt söker professionell hjälp med sin bilförsäljning.</p><div className="flex flex-col sm:flex-row gap-3 mt-9"><a href="/formedling/forhandlare" className="h-13 px-7 rounded-xl bg-white text-slate-900 font-semibold text-[15px] inline-flex items-center justify-center gap-2 hover:bg-slate-100 transition">Bli förmedlingspartner <ArrowRight className="w-4 h-4" /></a><a href="#hur" className="h-13 px-7 rounded-xl border border-white/15 text-white font-semibold text-[15px] inline-flex items-center justify-center hover:bg-white/5 transition">Se hur det fungerar</a></div></div><div className="rounded-2xl bg-white/5 border border-white/10 p-8"><div className="flex items-center gap-3 mb-8"><div className="w-12 h-12 rounded-xl bg-bilto-500/20 flex items-center justify-center"><Handshake className="w-6 h-6 text-bilto-400" /></div><div><p className="font-bold">Din partnerportal</p><p className="text-[13px] text-white/40">Nya möjligheter varje vecka</p></div></div>{[['Nya matchade bilar','12'],['Aktiva erbjudanden','8'],['Sålda denna månad','12']].map(([l,v]) => <div key={l} className="flex justify-between py-4 border-t border-white/8"><span className="text-[14px] text-white/50">{l}</span><span className="font-bold">{v}</span></div>)}</div></div></section>
      <section id="hur" className="bg-white text-slate-900 px-5 py-24"><div className="max-w-5xl mx-auto"><p className="text-[12px] font-bold text-slate-400 uppercase tracking-[.2em] mb-4">Därför Bilto</p><h2 className="text-[36px] sm:text-[48px] font-black tracking-tight mb-14">En enklare väg till fler uppdrag.</h2><div className="grid md:grid-cols-3 gap-5">{[{icon: Sparkles, title:'Ingen månadsavgift', text:'Du betalar endast när bilen faktiskt säljs.'},{icon: TrendingUp, title:'Välj själv', text:'Lämna erbjudanden på de bilar som passar er verksamhet.'},{icon: Wallet, title:'Tydlig ekonomi', text:'Se avgift, beräknad intäkt och uppdragets villkor innan du skickar.'}].map(c => {const Icon=c.icon; return <div key={c.title} className="bg-[#faf8f5] rounded-xl p-7"><div className="w-10 h-10 rounded-xl bg-white shadow-sm flex items-center justify-center mb-5"><Icon className="w-5 h-5 text-slate-700" /></div><h3 className="text-[18px] font-bold mb-2">{c.title}</h3><p className="text-[15px] text-slate-500 leading-relaxed">{c.text}</p></div>})}</div></div></section>
      <section className="px-5 py-24"><div className="max-w-2xl mx-auto text-center"><ShieldCheck className="w-10 h-10 text-bilto-400 mx-auto mb-5" /><h2 className="text-[36px] font-black">Redo att växa med oss?</h2><p className="text-white/50 mt-4">Ansök om att bli partner och börja se matchade bilar i portalen.</p><a href="/formedling/forhandlare" className="inline-flex items-center gap-2 h-12 px-7 mt-8 rounded-xl bg-white text-slate-900 font-semibold hover:bg-slate-100 transition">Öppna partnerdemo <ArrowRight className="w-4 h-4" /></a></div></section>
    </main>
  </div>;
}
