/*
  # Set cleaned_image_url for all catalog cars using imagin.studio transparent PNG URLs

  ## Summary
  Populates `cleaned_image_url` for all 318 cars that currently have Supabase Storage
  JPG images (which have white/grey backgrounds). Replaces them with imagin.studio URLs
  which return transparent PNG car renders — no white background, correct car colors.

  ## Changes
  - Sets `cleaned_image_url` for every car in car_catalog using the imagin.studio API
    format: `https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=X&modelFamily=Y&angle=23&width=600`
  - make and modelFamily values are mapped from the Swedish/local make/model names
  - Cars that already had imagin.studio image_url get their cleaned_image_url set too
    for consistency (useCarImages.ts prefers cleaned_image_url)

  ## Notes
  - imagin.studio returns transparent PNG renders — no CSS tricks needed
  - If imagin.studio doesn't have a model, it gracefully falls back to a generic render
  - The `angle=23` gives the standard 3/4 front-left perspective
*/

-- Helper: build imagin.studio URL
-- Format: make uses brand name, modelFamily uses model name with spaces replaced by hyphens

UPDATE car_catalog SET cleaned_image_url = CASE
  -- Alfa Romeo
  WHEN make = 'Alfa Romeo' AND model = 'Tonale' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Alfa-Romeo&modelFamily=Tonale&angle=23&width=600'
  WHEN make = 'Alfa Romeo' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Alfa-Romeo&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Audi
  WHEN make = 'Audi' AND model = 'A1' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A1&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A3 Sedan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A3 Sportback' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A4 Avant' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A4&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A5&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A6 Avant' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A6&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A7' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A7&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'A8' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=A8&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'e-tron' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=e-tron&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'e-tron GT' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=e-tron-GT&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q2' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q2&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q3 Sportback' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q4 e-tron' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q4-e-tron&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q4 e-tron Sportback' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q4-e-tron&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q5&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q6 e-tron' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q6-e-tron&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q7' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q7&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q8' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q8&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'Q8 e-tron' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=Q8-e-tron&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'RS3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=RS3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'RS3 Sedan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=RS3&angle=23&width=600'
  WHEN make = 'Audi' AND model = 'S3 Sedan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Audi&modelFamily=S3&angle=23&width=600'
  -- BMW
  WHEN make = 'BMW' AND model = '1-serie' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=1-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '2-serie Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=2-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '2-serie Gran Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=2-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '3-serie' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=3-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '3-serie Touring' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=3-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '4-serie Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=4-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '4-serie Gran Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=4-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '5-serie' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=5-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '6-serie GT' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=6-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = '7-serie' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=7-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'i4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=i4&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'i5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=i5&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'i7' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=i7&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'iX' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=iX&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'iX1' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=iX1&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'iX3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=iX3&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'M2' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=M2&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'M240i' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=2-series&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'M3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=M3&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'M3 Touring' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=M3&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'M4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=M4&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X1' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X1&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X2' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X2&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X3&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X4&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X5&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X6' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X6&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'X7' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=X7&angle=23&width=600'
  WHEN make = 'BMW' AND model = 'Z4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BMW&modelFamily=Z4&angle=23&width=600'
  -- BYD
  WHEN make = 'BYD' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=BYD&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Citroen
  WHEN make = 'Citroen' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Citroen&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Cupra
  WHEN make = 'Cupra' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Cupra&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Dacia
  WHEN make = 'Dacia' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Dacia&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- DS
  WHEN make = 'DS' AND model = '3 Crossback' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=DS&modelFamily=3&angle=23&width=600'
  WHEN make = 'DS' AND model = '4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=DS&modelFamily=4&angle=23&width=600'
  WHEN make = 'DS' AND model = '7 Crossback' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=DS&modelFamily=7&angle=23&width=600'
  WHEN make = 'DS' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=DS&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Fiat
  WHEN make = 'Fiat' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Fiat&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Ford
  WHEN make = 'Ford' AND model = 'Focus' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Focus&angle=23&width=600'
  WHEN make = 'Ford' AND model LIKE 'Focus%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Focus&angle=23&width=600'
  WHEN make = 'Ford' AND model = 'Kuga' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Kuga&angle=23&width=600'
  WHEN make = 'Ford' AND model = 'Mustang' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Mustang&angle=23&width=600'
  WHEN make = 'Ford' AND model = 'Mustang Mach-E' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Mustang-Mach-E&angle=23&width=600'
  WHEN make = 'Ford' AND model = 'Puma' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Puma&angle=23&width=600'
  WHEN make = 'Ford' AND model = 'Ranger' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=Ranger&angle=23&width=600'
  WHEN make = 'Ford' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Ford&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Genesis
  WHEN make = 'Genesis' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Genesis&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Honda
  WHEN make = 'Honda' AND model = 'Civic' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=Civic&angle=23&width=600'
  WHEN make = 'Honda' AND model = 'Civic Type R' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=Civic-Type-R&angle=23&width=600'
  WHEN make = 'Honda' AND model = 'CR-V' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=CR-V&angle=23&width=600'
  WHEN make = 'Honda' AND model = 'HR-V' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=HR-V&angle=23&width=600'
  WHEN make = 'Honda' AND model = 'Jazz' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=Jazz&angle=23&width=600'
  WHEN make = 'Honda' AND model = 'ZR-V' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=ZR-V&angle=23&width=600'
  WHEN make = 'Honda' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Honda&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Hyundai
  WHEN make = 'Hyundai' AND model = 'IONIQ 5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=IONIQ5&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'IONIQ 6' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=IONIQ6&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Kona Electric' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Kona&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Kona' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Kona&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Kona N' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Kona&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Tucson' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Tucson&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Santa Fe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Santa-Fe&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'i10' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=i10&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'i20' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=i20&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'i20 N' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=i20&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'i30' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=i30&angle=23&width=600'
  WHEN make = 'Hyundai' AND model LIKE 'i30%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=i30&angle=23&width=600'
  WHEN make = 'Hyundai' AND model = 'Bayon' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=Bayon&angle=23&width=600'
  WHEN make = 'Hyundai' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Hyundai&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Kia
  WHEN make = 'Kia' AND model = 'EV6' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=EV6&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'EV9' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=EV9&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Niro' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Niro&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Sportage' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Sportage&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Sorento' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Sorento&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Ceed' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Ceed&angle=23&width=600'
  WHEN make = 'Kia' AND model LIKE 'Ceed%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Ceed&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Picanto' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Picanto&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Rio' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Rio&angle=23&width=600'
  WHEN make = 'Kia' AND model = 'Stinger' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=Stinger&angle=23&width=600'
  WHEN make = 'Kia' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Kia&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Lamborghini
  WHEN make = 'Lamborghini' AND model = 'Aventador SVJ' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Lamborghini&modelFamily=Aventador&angle=23&width=600'
  WHEN make = 'Lamborghini' AND model = 'Huracan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Lamborghini&modelFamily=Huracan&angle=23&width=600'
  WHEN make = 'Lamborghini' AND model = 'Revuelto' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Lamborghini&modelFamily=Revuelto&angle=23&width=600'
  WHEN make = 'Lamborghini' AND model = 'Urus' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Lamborghini&modelFamily=Urus&angle=23&width=600'
  -- Land Rover
  WHEN make = 'Land Rover' AND model = 'Range Rover' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=Range-Rover&angle=23&width=600'
  WHEN make = 'Land Rover' AND model = 'Range Rover Sport' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=Range-Rover-Sport&angle=23&width=600'
  WHEN make = 'Land Rover' AND model = 'Range Rover Evoque' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=Range-Rover-Evoque&angle=23&width=600'
  WHEN make = 'Land Rover' AND model = 'Range Rover Velar' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=Range-Rover-Velar&angle=23&width=600'
  WHEN make = 'Land Rover' AND model = 'Discovery Sport' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=Discovery-Sport&angle=23&width=600'
  WHEN make = 'Land Rover' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Land-Rover&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Lexus
  WHEN make = 'Lexus' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Lexus&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Mercedes-Benz
  WHEN make = 'Mercedes-Benz' AND model = 'A-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=A-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'A45 AMG' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=A45-AMG&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'B-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=B-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'C-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=C-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'C-Klass Kombi' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=C-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'CLA' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=CLA&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'CLE Cabriolet' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=CLE&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'E-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=E-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'E-Klass Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=E-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'E-Klass Kombi' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=E-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'EQA' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=EQA&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'EQB' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=EQB&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'EQS SUV' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=EQS&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'G-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=G-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'GLA' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=GLA&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'GLB' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=GLB&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'GLC' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=GLC&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'GLC Coupe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=GLC-Coupe&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'GLE' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=GLE&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' AND model = 'V-Klass' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=V-Class&angle=23&width=600'
  WHEN make = 'Mercedes-Benz' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Mercedes-Benz&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- MINI
  WHEN make = 'MINI' AND model = 'Cooper' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=MINI&modelFamily=Cooper&angle=23&width=600'
  WHEN make = 'MINI' AND model = 'Countryman' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=MINI&modelFamily=Countryman&angle=23&width=600'
  WHEN make = 'MINI' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=MINI&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Nissan
  WHEN make = 'Nissan' AND model = 'Ariya' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Nissan&modelFamily=Ariya&angle=23&width=600'
  WHEN make = 'Nissan' AND model = 'Juke' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Nissan&modelFamily=Juke&angle=23&width=600'
  WHEN make = 'Nissan' AND model = 'Qashqai' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Nissan&modelFamily=Qashqai&angle=23&width=600'
  WHEN make = 'Nissan' AND model = 'X-Trail' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Nissan&modelFamily=X-Trail&angle=23&width=600'
  WHEN make = 'Nissan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Nissan&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Opel
  WHEN make = 'Opel' AND model = 'Corsa' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Opel&modelFamily=Corsa&angle=23&width=600'
  WHEN make = 'Opel' AND model = 'Crossland' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Opel&modelFamily=Crossland&angle=23&width=600'
  WHEN make = 'Opel' AND model = 'Grandland' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Opel&modelFamily=Grandland&angle=23&width=600'
  WHEN make = 'Opel' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Opel&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Peugeot
  WHEN make = 'Peugeot' AND model = '208' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=208&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '2008' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=2008&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '308' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=308&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '308 SW' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=308&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '3008' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=3008&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '408' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=408&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '508' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=508&angle=23&width=600'
  WHEN make = 'Peugeot' AND model LIKE '508%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=508&angle=23&width=600'
  WHEN make = 'Peugeot' AND model = '5008' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=5008&angle=23&width=600'
  WHEN make = 'Peugeot' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Peugeot&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Polestar
  WHEN make = 'Polestar' AND model = '2' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Polestar&modelFamily=2&angle=23&width=600'
  WHEN make = 'Polestar' AND model = '3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Polestar&modelFamily=3&angle=23&width=600'
  WHEN make = 'Polestar' AND model = '4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Polestar&modelFamily=4&angle=23&width=600'
  WHEN make = 'Polestar' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Polestar&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Porsche
  WHEN make = 'Porsche' AND model = '911' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=911&angle=23&width=600'
  WHEN make = 'Porsche' AND model = 'Cayenne' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=Cayenne&angle=23&width=600'
  WHEN make = 'Porsche' AND model = 'Macan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=Macan&angle=23&width=600'
  WHEN make = 'Porsche' AND model = 'Panamera' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=Panamera&angle=23&width=600'
  WHEN make = 'Porsche' AND model = 'Taycan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=Taycan&angle=23&width=600'
  WHEN make = 'Porsche' AND model LIKE '718%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=718&angle=23&width=600'
  WHEN make = 'Porsche' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Porsche&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Renault
  WHEN make = 'Renault' AND model = 'Clio' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Clio&angle=23&width=600'
  WHEN make = 'Renault' AND model = 'Captur' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Captur&angle=23&width=600'
  WHEN make = 'Renault' AND model = 'Arkana' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Arkana&angle=23&width=600'
  WHEN make = 'Renault' AND model = 'Austral' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Austral&angle=23&width=600'
  WHEN make = 'Renault' AND model = 'Zoe' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Zoe&angle=23&width=600'
  WHEN make = 'Renault' AND model = 'Megane E-Tech' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Megane&angle=23&width=600'
  WHEN make = 'Renault' AND model LIKE 'Megane%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Megane&angle=23&width=600'
  WHEN make = 'Renault' AND model LIKE 'Scenic%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=Scenic&angle=23&width=600'
  WHEN make = 'Renault' AND model = '5 E-Tech' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=5&angle=23&width=600'
  WHEN make = 'Renault' AND model = '4 E-Tech' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=4&angle=23&width=600'
  WHEN make = 'Renault' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Renault&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Seat
  WHEN make = 'Seat' AND model = 'Leon' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Seat&modelFamily=Leon&angle=23&width=600'
  WHEN make = 'Seat' AND model = 'Ibiza' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Seat&modelFamily=Ibiza&angle=23&width=600'
  WHEN make = 'Seat' AND model = 'Ateca' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Seat&modelFamily=Ateca&angle=23&width=600'
  WHEN make = 'Seat' AND model = 'Tarraco' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Seat&modelFamily=Tarraco&angle=23&width=600'
  WHEN make = 'Seat' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Seat&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Skoda
  WHEN make = 'Skoda' AND model = 'Octavia' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Octavia&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Octavia Combi' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Octavia&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Superb' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Superb&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Superb Combi' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Superb&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Fabia' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Fabia&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Enyaq' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Enyaq&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Karoq' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Karoq&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Kodiaq' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Kodiaq&angle=23&width=600'
  WHEN make = 'Skoda' AND model = 'Kamiq' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=Kamiq&angle=23&width=600'
  WHEN make = 'Skoda' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Skoda&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Suzuki
  WHEN make = 'Suzuki' AND model = 'Swift' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Suzuki&modelFamily=Swift&angle=23&width=600'
  WHEN make = 'Suzuki' AND model = 'Vitara' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Suzuki&modelFamily=Vitara&angle=23&width=600'
  WHEN make = 'Suzuki' AND model = 'Jimny' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Suzuki&modelFamily=Jimny&angle=23&width=600'
  WHEN make = 'Suzuki' AND model = 'S-Cross' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Suzuki&modelFamily=S-Cross&angle=23&width=600'
  WHEN make = 'Suzuki' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Suzuki&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Tesla
  WHEN make = 'Tesla' AND model = 'Model S' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Tesla&modelFamily=Model-S&angle=23&width=600'
  WHEN make = 'Tesla' AND model = 'Model X' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Tesla&modelFamily=Model-X&angle=23&width=600'
  WHEN make = 'Tesla' AND model = 'Model Y' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Tesla&modelFamily=Model-Y&angle=23&width=600'
  WHEN make = 'Tesla' AND model = 'Model 3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Tesla&modelFamily=Model-3&angle=23&width=600'
  WHEN make = 'Tesla' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Tesla&modelFamily=' || replace(replace(model, ' ', '-'), '.', '') || '&angle=23&width=600'
  -- Toyota
  WHEN make = 'Toyota' AND model = 'Yaris' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Yaris&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Yaris Cross' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Yaris-Cross&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Corolla' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Corolla&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Corolla Touring Sports' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Corolla&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'RAV4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=RAV4&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'C-HR' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=C-HR&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Prius' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Prius&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'GR Yaris' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=GR-Yaris&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Supra' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Supra&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Land Cruiser' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Land-Cruiser&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Hilux' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Hilux&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'Aygo X' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=Aygo&angle=23&width=600'
  WHEN make = 'Toyota' AND model = 'bZ4X' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=bZ4X&angle=23&width=600'
  WHEN make = 'Toyota' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Toyota&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  -- Volkswagen
  WHEN make = 'Volkswagen' AND model = 'Golf' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Golf&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model LIKE 'Golf%' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Golf&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID.3' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID3&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID.4' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID4&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID.5' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID5&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID.7' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID7&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID.7 Tourer' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID7&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'ID. Buzz' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=ID-Buzz&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Polo' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Polo&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Tiguan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Tiguan&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Touareg' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Touareg&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Passat Variant' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Passat&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'T-Roc' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=T-Roc&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'T-Roc Cabriolet' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=T-Roc&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'T-Cross' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=T-Cross&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Multivan' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Multivan&angle=23&width=600'
  WHEN make = 'Volkswagen' AND model = 'Transporter' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=Transporter&angle=23&width=600'
  WHEN make = 'Volkswagen' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volkswagen&modelFamily=' || replace(replace(model, 'ID.', 'ID'), ' ', '-') || '&angle=23&width=600'
  -- Volvo
  WHEN make = 'Volvo' AND model = 'XC90' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=XC90&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'XC60' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=XC60&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'XC40' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=XC40&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'XC40 Recharge' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=XC40-Recharge&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'XC70' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=XC70&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EX30' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EX30&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EX30 Cross Country' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EX30&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EX40' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EX40&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EX60' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EX60&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EX90' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EX90&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'EC40' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=EC40&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V60' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V60&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V60 Cross Country' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V60&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V70' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V70&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V90' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V90&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V90 Cross Country' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V90&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V40' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V40&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'V40 Cross Country' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=V40&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'S60' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=S60&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'S90' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=S90&angle=23&width=600'
  WHEN make = 'Volvo' AND model = 'C40 Recharge' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=C40-Recharge&angle=23&width=600'
  WHEN make = 'Volvo' THEN 'https://cdn.imagin.studio/getImage?customer=hrjavascript-mastery&make=Volvo&modelFamily=' || replace(model, ' ', '-') || '&angle=23&width=600'
  ELSE NULL
END
WHERE cleaned_image_url IS NULL OR cleaned_image_url = '';
